replicaCount: 3
image:
  repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
  tag: "2a23260e6b01802385db679f52f9c7398b6923aa"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  internalPort: 8080
resources:
  limits:
    cpu: "300m"
    memory: "256Mi"
  requests:
    cpu: "150m"
    memory: "128Mi"
migration:
  enabled: true
  backoffLimit: 2
  image:
    repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
    tag: "2a23260e6b01802385db679f52f9c7398b6923aa"
  command:
    - "sh"
    - "-c"
    - |-
      java -jar /app/app.jar --spring.flyway.enabled=true --spring.main.web-application-type=none
# Atenção: credenciais em claro para ambiente de desenvolvimento (não recomendado para produção)
database:
  host: "postgres.dev.svc.cluster.local"
  port: 5432
  name: "confeitaria_dev"
  user: "dev_user"
  password: "dev_password"
