replicaCount: 1
image:
  repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
  tag: "c62104463065829ea4ecd313c1111bd7b12b5563"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  internalPort: 8080
resources:
  limits:
    cpu: "300m"
    memory: "256Mi"
  requests:
    cpu: "150m"
    memory: "128Mi"
migration:
  enabled: true
  backoffLimit: 2
  image:
    repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
    tag: "4565d1fc0a068167da5fcae9a6a7dc3a4ea2f3ed"
  command: ["java", "-jar", "/app/migrate.jar"]

database:
  createSecret: false
  secretName: "postgres-dev-app"
  host: "postgres-dev-rw.myapp-dev.svc.cluster.local"
  port: 5432
  name: "appdb"
  user: "appuser"
