replicaCount: 1
image:
  repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
  tag: "6e485bffddf39c3852abc8e975d51c7c21676687"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  internalPort: 8080
resources:
  limits:
    cpu: "300m"
    memory: "256Mi"
  requests:
    cpu: "150m"
    memory: "128Mi"
migration:
  enabled: true
  backoffLimit: 2
  image:
    repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
    tag: "6e485bffddf39c3852abc8e975d51c7c21676687"
  command:
    - "sh"
    - "-c"
    - |-
      java -jar /app/app.jar --spring.flyway.enabled=true --spring.main.web-application-type=none
# Atenção: credenciais em claro para ambiente de desenvolvimento (não recomendado para produção)
database:
  host: "confeitaria-postgres"
  port: "5432"
  name: "confeitaria_dev"
  user: "dev_user"
  password: "dev_password"
