replicaCount: 1
image:
  repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
  tag: "a037f4d0bedfe1e9560d76ca354ce640de3ff92c"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  internalPort: 8080
resources:
  limits:
    cpu: "300m"
    memory: "256Mi"
  requests:
    cpu: "150m"
    memory: "128Mi"
migration:
  enabled: true
  backoffLimit: 2
  image:
    repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
    tag: "a037f4d0bedfe1e9560d76ca354ce640de3ff92c"
  command: ["java", "-jar", "/app/migrate.jar"]
database:
  createSecret: false
  secretName: "db-credentials"
  host: "postgres-dev-rw.myapp-dev.svc.cluster.local"
  port: 5432
  name: "appdb"
  user: "appuser"
