replicaCount: 2

image:
  repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
  tag: "4e1c2e4d319a1a2b8a1207ed33db6569bdc1b110"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  internalPort: 8080

resources:
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"

migration:
  enabled: true
  backoffLimit: 2
  image:
    repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
    tag: "4e1c2e4d319a1a2b8a1207ed33db6569bdc1b110"
  command: ["java", "-jar", "/app/app.jar", "--spring.flyway.enabled=true", "--spring.main.web-application-type=none"]

database:
  createSecret: false
  secretName: "db-credentials"
  host: "postgres-prod-rw.myapp-prod.svc.cluster.local"
  port: 5432
  name: "appdb"
  user: "appuser"
