replicaCount: 2
image:
  repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
  tag: "889dd8916225333a3d03705643dab14ee0da2a90"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  internalPort: 8080
resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
migration:
  enabled: true
  backoffLimit: 2
  image:
    repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
    tag: "889dd8916225333a3d03705643dab14ee0da2a90"
  command: ["java", "-jar", "/app/app.jar", "--spring.flyway.enabled=true", "--spring.main.web-application-type=none"]
database:
  createSecret: false
  secretName: "db-credentials"
  host: "postgres-prod-rw.myapp-prod.svc.cluster.local"
  port: 5432
  name: "appdb"
  user: "appuser"
rollout:
  enabled: true
  strategy: canary
