replicaCount: 3
image:
  repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
  tag: "4565d1fc0a068167da5fcae9a6a7dc3a4ea2f3ed"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  internalPort: 8080
resources:
  limits:
    cpu: "300m"
    memory: "256Mi"
  requests:
    cpu: "150m"
    memory: "128Mi"
migration:
  enabled: true
  backoffLimit: 2
  image:
    repository: "ghcr.io/igorbatistadev/confeitaria-backend-devops"
    tag: "4565d1fc0a068167da5fcae9a6a7dc3a4ea2f3ed"
  command: ["java", "-jar", "/app/migrate.jar"]
# Atenção: credenciais em claro para ambiente de desenvolvimento (não recomendado para produção)
database:
  host: "postgres.dev.svc.cluster.local"
  port: 5432
  name: "confeitaria_dev"
  user: "dev_user"
  password: "dev_password"
