apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.user | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:5432/%s" .Values.database.host .Values.database.name | b64enc | quote }}
  SPRING_FLYWAY_URL: {{ printf "jdbc:postgresql://%s:5432/%s" .Values.database.host .Values.database.name | b64enc | quote }}
  SPRING_FLYWAY_USER: {{ .Values.database.user | b64enc | quote }}
  SPRING_FLYWAY_PASSWORD: {{ .Values.database.password | b64enc | quote }}