apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  DB_PASS: {{ .Values.database.password | b64enc | quote }}
  DB_HOST: {{ .Values.database.host | b64enc | quote }}
  DB_NAME: {{ .Values.database.name | b64enc | quote }}