apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    {{ include "confeitaria.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "confeitaria.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "confeitaria.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "confeitaria.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          # Injetar vari√°veis do secret do CloudNativePG
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ (print "jdbc:postgresql://" .Values.database.host ":" .Values.database.port "/" .Values.database.name) | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db-secret" .Release.Name) .Values.database.secretName | quote }}
                  key: {{ default "username" .Values.database.usernameKey | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db-secret" .Release.Name) .Values.database.secretName | quote }}
                  key: {{ default "password" .Values.database.passwordKey | quote }}
            - name: SPRING_FLYWAY_URL
              value: {{ (print "jdbc:postgresql://" .Values.database.host ":" .Values.database.port "/" .Values.database.name) | quote }}
            - name: SPRING_FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db-secret" .Release.Name) .Values.database.secretName | quote }}
                  key: {{ default "username" .Values.database.usernameKey | quote }}
            - name: SPRING_FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db-secret" .Release.Name) .Values.database.secretName | quote }}
                  key: {{ default "password" .Values.database.passwordKey | quote }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 1200
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 1200
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
