{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "confeitaria.fullname" . }}-migrations
  labels:
    {{ include "confeitaria.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  backoffLimit: {{ default 4 .Values.migration.backoffLimit }}
  template:
    metadata:
      labels:
        {{ include "confeitaria.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate

          {{- if .Values.migration.image.repository }}
          image: |  
            {{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}
          {{- else }}
          image: |  
            {{ .Values.image.repository }}:{{ .Values.image.tag }}
          {{- end }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.migration.image.pullPolicy }}
          command: {{ toYaml .Values.migration.command | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-db-secret
      activeDeadlineSeconds: {{ default 600 .Values.migration.activeDeadlineSeconds }}
{{- end }}
