{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ include "confeitaria.fullname" . }}-migrations-
  labels:
    {{ include "confeitaria.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ default 4 .Values.migration.backoffLimit }}
  template:
    metadata:
      labels:
        {{ include "confeitaria.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          {{- if .Values.migration.image.repository }}
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.migration.image.pullPolicy }}
          command: {{ toYaml .Values.migration.command | nindent 12 }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ (print "jdbc:postgresql://" .Values.database.host ":" .Values.database.port "/" .Values.database.name) | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db-secret" .Release.Name) .Values.database.secretName | quote }}
                  key: {{ default "username" .Values.database.usernameKey | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db-secret" .Release.Name) .Values.database.secretName | quote }}
                  key: {{ default "password" .Values.database.passwordKey | quote }}
            - name: SPRING_FLYWAY_URL
              value: {{ (print "jdbc:postgresql://" .Values.database.host ":" .Values.database.port "/" .Values.database.name) | quote }}
            - name: SPRING_FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db-secret" .Release.Name) .Values.database.secretName | quote }}
                  key: {{ default "username" .Values.database.usernameKey | quote }}
            - name: SPRING_FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db-secret" .Release.Name) .Values.database.secretName | quote }}
                  key: {{ default "password" .Values.database.passwordKey | quote }}

  activeDeadlineSeconds: {{ default 600 .Values.migration.activeDeadlineSeconds }}
{{- end }}
