{{- if .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-db-secret" .Release.Name) .Values.database.secretName }}
  labels:
    {{ include "confeitaria.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.user | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  SPRING_DATASOURCE_URL: {{ (print "jdbc:postgresql://" .Values.database.host ":" .Values.database.port "/" .Values.database.name) | b64enc | quote }}
  SPRING_FLYWAY_URL: {{ (print "jdbc:postgresql://" .Values.database.host ":" .Values.database.port "/" .Values.database.name) | b64enc | quote }}
  SPRING_FLYWAY_USER: {{ .Values.database.user | b64enc | quote }}
  SPRING_FLYWAY_PASSWORD: {{ .Values.database.password | b64enc | quote }}
{{- end }}
