---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-stable
  labels:
    {{ include "confeitaria.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "confeitaria.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-canary
  labels:
    {{ include "confeitaria.labels" . | nindent 4 }}
    service-type: canary
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "confeitaria.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}