{{- if eq .Release.Namespace "myapp-dev" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-active
  labels:
    {{ include "confeitaria.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "confeitaria.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-preview
  labels:
    {{ include "confeitaria.labels" . | nindent 4 }}
    service-type: preview
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "confeitaria.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}